manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/arcanemachine
  projects:
    - name: zmk
      remote: zmk-ergo-s-1
      revision: main
      import: app/west.yml
  self:
    path: config
