manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/wizarddata
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: Ergo_S-1_OE
      import: app/west.yml
  self:
    path: config
