manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/arcanemachine
  projects:
    - name: zmk-ergo-s-1
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
